### ISSUE TITLE
Should we update Processing?

### ISSUE THREAD

**Issue by j08lue** [TIGER-NET/WOIS_Installer#19]
We are currently including the version from QGIS release 2.14 (https://github.com/DHI-GRAS/ESA_Processing).

Should we update it to 2.18 (https://github.com/qgis/QGIS/tree/release-2_18)?

@radosuav I know you can probably answer this straight away? :-)

**Comment by radosuav** [comment]
The general idea is to stick with QGIS LTR which currently is version 2.14. But because 2.18 is the last release of the 2.x series and because the next LTR won't be out until well into the second half of this year (due to longer development cycle of QGIS 3.0) it makes sense to update to 2.18. 

Note that QGIS itself should also be updated to 2.18 (not just Processing).

**Comment by j08lue** [comment]
We chose to update both QGIS and Processing to 2.18.

There are two fixes that you @radosuav provided, which now got overwritten, but both are already included upstream:

- https://github.com/DHI-GRAS/ESA_Processing/commit/fb92d3576ff32af3d3ecb691c0ea1a9632b54e70 is now https://github.com/qgis/QGIS/blob/release-2_18/python/plugins/processing/gui/ConfigDialog.py#L348
- https://github.com/DHI-GRAS/ESA_Processing/commit/e7ddb3ad8181f28e9a308523dbbfbad4ae7bd06f is now https://github.com/qgis/QGIS/blob/release-2_18/python/plugins/processing/modeler/ModelerAlgorithm.py#L214-L217
