### ISSUE TITLE
WOIS 4.1 installer asking for .NET Framework 3.5

### ISSUE THREAD

**Issue by ctottrup** [TIGER-NET/WOIS_Installer#20]
It is possible to download and install .NET Framework 3.5 during WOIS installation but since we want the installer to work offline this is not optimal.

**Comment by radosuav** [comment]
Which software is asking for .NET? I don't remember this dependency from before.

**Comment by ctottrup** [comment]
It was MWSWAT or MapWindow can't remember

**Comment by ctottrup** [comment]
I think it is teh QSWAT supprot which has been added to PG09 that is causing the dependency -> http://swat.tamu.edu/software/qswat/

**Comment by radosuav** [comment]
Is MWSWAT being updated in the new WOIS release? 

In WOIS 4.0 we used SWAT Editor 2009 which requires .NET Framework 2.0. Also QSWAT 1.3 works with MWSWAT 2009.

On 02.02.2017 QSWAT 1.4 was released. It requires SWAT Editor 2012.10.19 which in turn requires .NET Framework 3.5. 

I guess that .NET 2.0 was already installed on all the computers while this is not the case with .NET 3.5.

**Comment by ctottrup** [comment]
should not be the case - but we have to ask @j08lue

**Comment by j08lue** [comment]
I don't think this has anything to do with QSWAT. 

The request to install .NET 3.5 (which also includes 2.0 support) pops up when the binary installers for MWSWAT or MapWindow starts. I cannot remember which, either (will check!). But this was actually the same with the last WOIS release, when installing it on a clean Windows 10 VM.  Therefore I did not think this was an (unknown) issue.

My impression is that Windows machines with a history often already have one or several versions of .NET installed from other software requirements. Therefore, this mostly becomes apparent on a clean machine.

So chances are that WOIS users already have .NET on their machine. Otherwise, it is only a small download for the user. 

I can also try to include the offline installer so we can include it with the package, if you would prefer that. But I would rather not have to, given that many users probably already have it or can download it cheaply. What do you reckon, @radosuav?

**Comment by radosuav** [comment]
I agree that most people should have it already and it affects only SWAT which is not a fundamental part of WOIS. Maybe just add the offline .net installer to the "MWSWAT additional software" folder and write some short info in the troubleshooting section of the manual but don't update the actual WOIS installer program?

**Comment by j08lue** [comment]
That would be a good solution, @radosuav.

However, I am unable to find an official offline installer for .NET Framework 3.5. I remember trying for a while when testing WOIS 4.0, at that time just to save time during repeated installation. 

There is this package: https://www.microsoft.com/en-us/download/details.aspx?id=65 but that does not seem to be the complete framework, but only an update / Service Pack?

Some people apparently [made their own offline installers](http://www.askvg.com/download-microsoft-net-framework-3-5-offline-installer-for-windows-8/), but I would not want to distribute those.

Just for the record, this is the link to the network installer https://www.microsoft.com/en-us/download/details.aspx?id=21.

**Comment by j08lue** [comment]
> pops up when the binary installers for MWSWAT or MapWindow starts. I cannot remember which, either (will check!)

The check for .NET comes when clicking "contineu" on the first dialogue after the PostGIS installation (which is MapWindow), but seems to be woven into the SWAT / MapWindow installers.

**Comment by j08lue** [comment]
> Is MWSWAT being updated in the new WOIS release?

Sorry I never answered this - no, we did not update any of those components.

**Comment by j08lue** [comment]
> There is this package: https://www.microsoft.com/en-us/download/details.aspx?id=65

Sorry, I meant this one: https://www.microsoft.com/en-us/download/details.aspx?id=25150

**Comment by j08lue** [comment]
I suggest we do not do anything about this. The few users who might be affected by this are guided quite well by the installer to fetch the missing .NET framework and it probably does not pull much more than 30 MB (referencing the [SP package](https://www.microsoft.com/en-us/download/details.aspx?id=25150) I mentioned above).

**Comment by j08lue** [comment]
@ctottrup agreed that we do not do anything about the .NET requirement.
